stages:
  - test
  - build


PEP8_compliance:
  stage: test
  
  image: python:3.5

  before_script:
    - pip3.5 install pycodestyle
  
  script: pycodestyle */*.py || true

Coverage_tests:
  stage: test
  
  image: python:3.5

  before_script:
    - pip3.5 install coverage
    - pip3.5 install -r requirements.txt
  
  script:
    - coverage run -a shared/iftools.py
    - coverage run -a shared/api_wrapper.py
    - coverage run -a shared/dnstools.py
    - coverage report
  

build_api:
  stage: build
  
  image: docker:git

  services:
  - docker:dind

  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - cp -rfp requirements.txt core/.
    - docker build -t registry.gitlab.com/gbnk0/nmt/core -f docker/dockerfile-core .
    - docker push registry.gitlab.com/gbnk0/nmt/core:latest


build_web:
  stage: build
  
  image: docker:git

  services:
  - docker:dind

  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbnk0/nmt/web -f docker/dockerfile-web .
    - docker push registry.gitlab.com/gbnk0/nmt/web:latest